services:
  website:
    image: ghcr.io/abstractumbra/terrible-website:latest
    container_name: "website"
    restart: "unless-stopped"
    volumes:
      - ./static:/app/static:ro
      - ./templates:/app/templates:ro
      - ./resources:/app/resources:ro
    ports:
      - 8030:8030
