name: docker-build-and-push-ci

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

concurrency:
  cancel-in-progress: true
  group: ci-${{ github.ref }}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-build-image:
    runs-on: ubuntu-latest
    env:
      GIT_SHA: ${GITHUB_SHA::7}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}

      - name: Generate lowername image
        id: image-name
        run: |
          echo "IMAGE_NAME_LC=${IMAGE_NAME,,}" >> "${GITHUB_OUTPUT}"
        env:
          IMAGE_NAME: "${{ env.IMAGE_NAME }}"

      - name: Get short SHA
        id: slug
        run: echo "GIT_SHORT_SHA7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REGISTRY}}/${{ steps.image-name.outputs.IMAGE_NAME_LC }}:${{ steps.slug.outputs.GIT_SHORT_SHA7 }}
            ${{ env.REGISTRY}}/${{ steps.image-name.outputs.IMAGE_NAME_LC }}:latest
          labels: ${{ steps.meta.outputs.labels }}
